### PR TITLE
google-cloud-sdk package was deleted from Ubuntu canonical partner repository

### PR DESCRIPTION
**Pull request by e-koma**
## Issue
Since 2021/01/15, Ubuntu canonical partner repository is no longer support google-cloud-sdk.
current GCE google-cloud-sdk install way fails.
https://www.ubuntuupdates.org/package/canonical_partner/bionic/partner/base/google-cloud-sdk

I fixed startup-script and tested it.

## Error
GCE startup-script, which used to succeed, now fails.

```
Jan 19 06:11:42 forseti-server-vm-dev systemd[1]: Starting Google Compute Engine Startup Scripts...
Jan 19 06:11:42 forseti-server-vm-dev startup-script: INFO Starting startup scripts.
Jan 19 06:11:42 forseti-server-vm-dev startup-script: INFO Found startup-script in metadata.
Jan 19 06:11:42 forseti-server-vm-dev startup-script: INFO startup-script: Forseti Startup - Updating Ubuntu.
Jan 19 06:11:42 forseti-server-vm-dev startup-script: INFO startup-script: Hit:1 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu bionic InRelease
Jan 19 06:11:42 forseti-server-vm-dev startup-script: INFO startup-script: Get:2 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Jan 19 06:11:42 forseti-server-vm-dev startup-script: INFO startup-script: Get:3 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Jan 19 06:11:42 forseti-server-vm-dev startup-script: INFO startup-script: Get:4 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [8570 kB]
Jan 19 06:11:42 forseti-server-vm-dev startup-script: INFO startup-script: Get:5 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Jan 19 06:11:43 forseti-server-vm-dev startup-script: INFO startup-script: Get:6 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu bionic/universe Translation-en [4941 kB]
Jan 19 06:11:43 forseti-server-vm-dev startup-script: INFO startup-script: Get:7 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [151 kB]
Jan 19 06:11:43 forseti-server-vm-dev startup-script: INFO startup-script: Get:8 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu bionic/multiverse Translation-en [108 kB]
Jan 19 06:11:43 forseti-server-vm-dev startup-script: INFO startup-script: Get:9 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1843 kB]
Jan 19 06:11:43 forseti-server-vm-dev startup-script: INFO startup-script: Get:10 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1705 kB]
Jan 19 06:11:43 forseti-server-vm-dev startup-script: INFO startup-script: Get:11 http://archive.canonical.com/ubuntu bionic InRelease [10.2 kB]
Jan 19 06:11:43 forseti-server-vm-dev startup-script: INFO startup-script: Get:12 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu bionic-updates/universe Translation-en [359 kB]
Jan 19 06:11:43 forseti-server-vm-dev startup-script: INFO startup-script: Get:13 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [31.7 kB]
Jan 19 06:11:43 forseti-server-vm-dev startup-script: INFO startup-script: Get:14 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu bionic-updates/multiverse Translation-en [6696 B]
Jan 19 06:11:43 forseti-server-vm-dev startup-script: INFO startup-script: Get:15 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [10.0 kB]
Jan 19 06:11:43 forseti-server-vm-dev startup-script: INFO startup-script: Get:16 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu bionic-backports/main Translation-en [4764 B]
Jan 19 06:11:43 forseti-server-vm-dev startup-script: INFO startup-script: Get:17 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [10.3 kB]
Jan 19 06:11:43 forseti-server-vm-dev startup-script: INFO startup-script: Get:18 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu bionic-backports/universe Translation-en [4588 B]
Jan 19 06:11:44 forseti-server-vm-dev startup-script: INFO startup-script: Get:19 http://archive.canonical.com/ubuntu bionic/partner amd64 Packages [1592 B]
Jan 19 06:11:44 forseti-server-vm-dev startup-script: INFO startup-script: Get:20 http://archive.canonical.com/ubuntu bionic/partner Translation-en [1004 B]
Jan 19 06:11:44 forseti-server-vm-dev startup-script: INFO startup-script: Get:21 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1512 kB]
Jan 19 06:11:45 forseti-server-vm-dev startup-script: INFO startup-script: Get:22 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en [293 kB]
Jan 19 06:11:45 forseti-server-vm-dev startup-script: INFO startup-script: Get:23 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1099 kB]
Jan 19 06:11:45 forseti-server-vm-dev startup-script: INFO startup-script: Get:24 http://security.ubuntu.com/ubuntu bionic-security/universe Translation-en [246 kB]
Jan 19 06:11:45 forseti-server-vm-dev startup-script: INFO startup-script: Get:25 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [12.5 kB]
Jan 19 06:11:45 forseti-server-vm-dev startup-script: INFO startup-script: Get:26 http://security.ubuntu.com/ubuntu bionic-security/multiverse Translation-en [2644 B]
Jan 19 06:11:50 forseti-server-vm-dev startup-script: INFO startup-script: Fetched 21.2 MB in 5s (4649 kB/s)
Jan 19 06:11:51 forseti-server-vm-dev startup-script: INFO startup-script: Reading package lists...
Jan 19 06:11:51 forseti-server-vm-dev startup-script: INFO startup-script: Reading package lists...
Jan 19 06:11:51 forseti-server-vm-dev startup-script: INFO startup-script: Building dependency tree...
Jan 19 06:11:51 forseti-server-vm-dev startup-script: INFO startup-script: Reading state information...
Jan 19 06:11:51 forseti-server-vm-dev startup-script: INFO startup-script: Calculating upgrade...
Jan 19 06:11:52 forseti-server-vm-dev startup-script: INFO startup-script: The following package was automatically installed and is no longer required:
Jan 19 06:11:52 forseti-server-vm-dev startup-script: INFO startup-script:   libnuma1
Jan 19 06:11:52 forseti-server-vm-dev startup-script: INFO startup-script: Use 'sudo apt autoremove' to remove it.
Jan 19 06:11:52 forseti-server-vm-dev startup-script: INFO startup-script: 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Jan 19 06:11:52 forseti-server-vm-dev startup-script: INFO startup-script: Hit:1 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu bionic InRelease
Jan 19 06:11:52 forseti-server-vm-dev startup-script: INFO startup-script: Hit:2 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu bionic-updates InRelease
Jan 19 06:11:52 forseti-server-vm-dev startup-script: INFO startup-script: Hit:3 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu bionic-backports InRelease
Jan 19 06:11:52 forseti-server-vm-dev startup-script: INFO startup-script: Hit:4 http://archive.canonical.com/ubuntu bionic InRelease
Jan 19 06:11:52 forseti-server-vm-dev startup-script: INFO startup-script: Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease
Jan 19 06:11:54 forseti-server-vm-dev startup-script: INFO startup-script: Reading package lists...
Jan 19 06:11:54 forseti-server-vm-dev startup-script: INFO startup-script: Reading package lists...
Jan 19 06:11:54 forseti-server-vm-dev startup-script: INFO startup-script: Building dependency tree...
Jan 19 06:11:54 forseti-server-vm-dev startup-script: INFO startup-script: Reading state information...
Jan 19 06:11:55 forseti-server-vm-dev startup-script: INFO startup-script: No apt package "google-cloud-sdk", but there is a snap with that name.
Jan 19 06:11:55 forseti-server-vm-dev startup-script: INFO startup-script: Try "snap install google-cloud-sdk"
Jan 19 06:11:55 forseti-server-vm-dev startup-script: INFO startup-script: E: Unable to locate package google-cloud-sdk
Jan 19 06:11:55 forseti-server-vm-dev startup-script: INFO startup-script: Return code 100.
Jan 19 06:11:55 forseti-server-vm-dev startup-script: INFO Finished running startup scripts.
```

## After Fixed it

It works properly.

```
startup-script: INFO startup-script: Forseti Startup - Execution of startup script finished.
startup-script: INFO startup-script: Return code 0.
startup-script: INFO Finished running startup scripts.
```

### CODE REVIEW

**Review by browningjp — CHANGES_REQUESTED** [review]
Since the Google Cloud SDK is already installed on GCE instances by default, we don't actually need to install it here, so we can simply remove `google-cloud-sdk` from `sudo apt-get --assume-yes install google-cloud-sdk git unzip`

**Comment by e-koma** [comment]
thanks !!
I was able to check it and fixed it.

**Comment by rogeriobastos** [comment]
Hi, why this was not merged into modulerelease522 branch ?

**Comment by e-koma** [comment]
If no one reviews, it seems to close automatically by bot.
Without merging this Pull Request, modulerelease522 will not work now... :sob::sob::sob:

There are people in the slack community who regularly encounter this problem.
Each time, I tell them that this is the way to fix it.
I want to merge this Pull Request.

**Pull request closed without merging**
