### PR TITLE
Allow CIS image to work

### PR DESCRIPTION
**Pull request by choonchernlim**
This PR makes slight tweaks to `forseti_server_startup_script.sh.tpl` to:-
- Allow [CIS Level 1 image](https://console.cloud.google.com/marketplace/details/cis-public/cis-ubuntu-linux-1804-level-1?q=CIS%20ubuntu&id=b8c19017-68eb-4da0-b83a-b432136685d4) to work (requirement from my institution).
	- Gracefully wait for lock(s) on file to be released.
	- Allow `ubuntu` user to use crontab. Note: This disables one of the controls from CIS Level 1 specs.
- Ensure [AppArmor is always enabled](https://wiki.debian.org/AppArmor/HowToUse#Enable_AppArmor).

Tested to work with the following images:-
- CIS Level 1 image: `cis-public/cis-ubuntu-linux-1804-level-1-v1-0-0-12`
- Shielded image: `gce-uefi-images/ubuntu-1804-lts`
- Non-Shielded image: `ubuntu-os-cloud/ubuntu-1804-lts`

Note: These changes are provided/verified by several UNIX experts from my institution to satisfy requirements from the security team. Thank you.

**BEFORE**

```
$ cat /etc/cron.allow
cat: /etc/cron.allow: No such file or directory

$cat /etc/default/grub.d/50-cloudimg-settings.cfg 
# CLOUD_IMG: This file was created/modified by the Cloud Image build process
GRUB_DEFAULT=0
GRUB_HIDDEN_TIMEOUT=0.1
GRUB_HIDDEN_TIMEOUT_QUIET=true
GRUB_TIMEOUT=0.1
GRUB_CMDLINE_LINUX_DEFAULT="console=ttyS0"
GRUB_CMDLINE_LINUX="scsi_mod.use_blk_mq=Y"
GRUB_RECORDFAIL_TIMEOUT=0
GRUB_TERMINAL=console

$ grep "^\s*linux" /boot/grub/grub.cfg | grep -v "apparmor=1"                                 
linux   /boot/vmlinuz-5.0.0-1031-gcp root=UUID=c3cf7343-f90e-488d-bf05-6ee2d8418e4c ro scsi_mod.use_blk_mq=Y console=ttyS0
linux   /boot/vmlinuz-5.0.0-1031-gcp root=UUID=c3cf7343-f90e-488d-bf05-6ee2d8418e4c ro scsi_mod.use_blk_mq=Y console=ttyS0
linux   /boot/vmlinuz-5.0.0-1031-gcp root=UUID=c3cf7343-f90e-488d-bf05-6ee2d8418e4c ro recovery nomodeset scsi_mod.use_blk_mq=Y
linux   /boot/vmlinuz-5.0.0-1029-gcp root=UUID=c3cf7343-f90e-488d-bf05-6ee2d8418e4c ro scsi_mod.use_blk_mq=Y console=ttyS0
linux   /boot/vmlinuz-5.0.0-1029-gcp root=UUID=c3cf7343-f90e-488d-bf05-6ee2d8418e4c ro recovery nomodeset scsi_mod.use_blk_mq=Y
```

**AFTER**

```
$ cat /etc/cron.allow
root
ubuntu

$ cat /etc/default/grub.d/50-cloudimg-settings.cfg 
# CLOUD_IMG: This file was created/modified by the Cloud Image build process
GRUB_DEFAULT=0
GRUB_HIDDEN_TIMEOUT=0.1
GRUB_HIDDEN_TIMEOUT_QUIET=true
GRUB_TIMEOUT=0.1
GRUB_CMDLINE_LINUX_DEFAULT="console=ttyS0"
GRUB_CMDLINE_LINUX="scsi_mod.use_blk_mq=Y apparmor=1 security=apparmor"
GRUB_RECORDFAIL_TIMEOUT=0
GRUB_TERMINAL=console

$ grep "^\s*linux" /boot/grub/grub.cfg | grep -v "apparmor=1"
[no results]
```

### CODE REVIEW

**Comment by choonchernlim** [comment]
@morgante @xingao267 : Can you let me know the error message? Thank you.

**Comment by hshin-g** [comment]
@choonchernlim Would you be able to resolve the branch conflicts? Once those are pushed in and the tests pass, we can merge this in- thanks!

**Comment by red2k18** [comment]
@choonchernlim , thanks for the PR! Some of the tests are failing. Would you be able to look into it so we can get this PR merged in?

**Comment by choonchernlim** [comment]
@red2k18 Can you let me know the detailed errors? I have no access to your CI. Thanks.

**Comment by red2k18** [comment]
Forseti server instance resources (4 failed)

image

**Comment by choonchernlim** [comment]
Are the tests failing for just `install_simple` or multiple places? I know the test structure was drastically refactored.

**Comment by red2k18** [comment]
Tests are failing for `install_simple`, `private_connection` and `shared_vpc` profiles.

**Comment by red2k18** [comment]
@choonchernlim , thanks for fixing the tests! @gkowalski-google , please look over and merge it in if all looks good.

**Pull request merged**
