### PR TITLE
Allow user to configure Scanner Rules path to GCS or local dir

### PR DESCRIPTION
**Pull request by mcapts**
This PR will allow a Terraform Forseti user to provide a rules_path as input to the top-level forseti module, and have that propagate down into the server_config module. We have tested to ensure this works with a GCS path only (not a local dir, although that is the default behavior so this should not affect that). @blueandgold

### CODE REVIEW

**Comment by kevensen** [comment]
Hi @mcapts Thanks for this PR.  This is a useful addition.  Are you able to sign the CLA?

**Comment by mcapts** [comment]
@googlebot I signed it!

**Comment by blueandgold** [comment]
@googlebot rescan

**Comment by blueandgold** [comment]
@googlebot rescan

**Comment by gkowalski-google** [comment]
@mcapts Hello, sorry we have not merged this yet. We are fixing some issues with the build and then will get this merged in.

**Pull request merged**
