### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by Ian-Harris**
Addresses [issue 153](https://github.com/forseti-security/terraform-google-forseti/issues/153) 
The Cloud SQL resource is (correctly) defined with `settings.0.disk_autoresize:"true"`, so ignoring changes to `settings.0.disk_size` prevents issues with later reruns of terraform.

### CODE REVIEW

**Comment by Ian-Harris** [comment]
CLA signed

**Comment by kevensen** [comment]
@morgante @aaron-lane @Ian-Harris What is required to get this change over the finish line?

**Comment by morgante** [comment]
The merge conflicts need to be fixed.

**Comment by kevensen** [comment]
@morgante ack, thx.  @Ian-Harris at your convenience do you mind taking a look at the merge conflicts?

**Comment by kevensen** [comment]
Hi @Ian-Harris.  I am closing this for now.  Please feel free to reopen if you'd still like to get this merged.

**Pull request closed without merging**
