### PR TITLE
Handling case for upgrading using Terraform

### PR DESCRIPTION
**Pull request by kevensen**
The Forseti Python installer names the allow-ssh firewall rules:

- forseti-server-allow-ssh-external-$RESOURCE_NAME_SUFFIX
- forseti-client-allow-ssh-external-$RESOURCE_NAME_SUFFIX

The Terraform installer names them:
- forseti-server-ssh-external-$RESOURCE_NAME_SUFFIX
- forseti-client-ssh-external-$RESOURCE_NAME_SUFFIX

As a user of Forseti, I want to use the import.sh script to import state from a previous install using Terraform, so that I can tolerate major changes to the terraform-google-forseti module.

### CODE REVIEW

**Comment by gkowalski-google** [comment]
@kevensen LGTM. Can you please update the [website documentation](https://forsetisecurity.org/docs/latest/setup/migrate.html#destroyed-and-replaced) if necessary?

**Comment by kevensen** [comment]
Repeated lint test failure:

```
test/terraform_validate ./test/fixtures/real_time_enforcer_roles 

Error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: context deadline exceeded"
```
I don't think this is related to the changes in this PR.

**Comment by kevensen** [comment]
@gkowalski-google You raise a good point, thanks.  I reviewed current documentation and I don't think that this change requires an update at this time.  The scenario is that users will use this script to migrate from the Python installer to Terraform.  Existing docs still apply.

However, there will need to be a documentation update when we refactor the sub-modules (again) and ask users to migrate from 4.x to 5.0.

**Comment by gkowalski-google** [comment]
@hshin-g @kevensen This PR needs to be merged before release testing can be completed. In the future, can we merge PRs once they are approved?

**Pull request merged**
