### PR TITLE
Add policy_library_repository_branch to GCE module

### PR DESCRIPTION
**Pull request by hshin-g**
Addresses #366

### CODE REVIEW

**Comment by hshin-g** [comment]
@gkowalski-google No, does there need to be if it's specific to the Terraform module?

**Comment by gkowalski-google** [comment]
> @gkowalski-google No, does there need to be if it's specific to the Terraform module?

Ticket not necessary, but the [initialize forseti services script](https://github.com/forseti-security/forseti-security/blob/master/install/gcp/scripts/initialize_forseti_services.sh#L56) will need to use this variable. Please default to master if none provided.

**Comment by kevensen** [comment]
@hshin-g Do you mind updating your branch?  It should clear up the lint and integration tests.

**Comment by hshin-g** [comment]
Ok that makes sense- thanks for the heads up @gkowalski-google! Will submit a PR for that as well.

Have merged in master- thanks Ken!

**Pull request merged**
