### PR TITLE
Separate Out CloudSQL component

### PR DESCRIPTION
**Pull request by kevensen**
This is an attempt at sub-modularization.  I wanted to try a single, common resource for starters.

### CODE REVIEW

**Comment by hshin-g** [comment]
@kevensen Thanks for submitting this. What is the rationale for separating out CloudSQL as a submodule?

**Comment by kevensen** [comment]
The rationale being that we want to get to a place where if the user wants to go the GKE route, they don't end up with a server vm.  This is the first attempt of what will be a separation of resources that are common to both the GCE install and GKE install.

**Comment by hshin-g** [comment]
Ok thanks for the explanation. Is this something that we want to do for the 2.19 Forseti release, or is this something that can be pushed to 2.20?

**Comment by kevensen** [comment]
Definitely 2.20

**Comment by kevensen** [comment]
This is superseded by #228

**Pull request closed without merging**
