### PR TITLE
Add READMEs to submodules

### PR DESCRIPTION
**Pull request by hshin-g**
Related to #264 

Added READMEs to submodules for user readability and accessibility.

### CODE REVIEW

**Comment by morgante** [comment]
@hshin-g @kevensen FYI I would suggest *not* having readmes on "internal" modules unless we expect users to be directly instantiating them. I don't think users would directly instantiate these submodules themselves, would they?

https://www.terraform.io/docs/modules/#standard-module-structure

**Comment by hshin-g** [comment]
I think there is always at least some possibility of users instantiating the submodules themselves, and if there are users who want to contribute to this module, it would help to be able to break down what each of these modules do at the get-go for easier digestion. We can always take out the READMEs if you'd prefer, but I think that having more documentation isn't necessarily a bad thing.

**Comment by kevensen** [comment]
FWIW, I am rolling this back as part of the submodule rollback.  We can discuss this more in the coming days.

**Comment by kevensen** [comment]
After some more thought, I would add that most of the submodules have dependencies on the other submodules, so instantiating them individually is probably an unlikely scenario.

**Comment by morgante** [comment]
While users *can* still instantiate internal modules themselves, exposing them with a README adds them to the public/documented surface of the module. Meaning we have to be careful about changes in the submodules mark versioned changes.

I'd recommend keeping them internal (and not having READMEs) unless there's a compelling reason to encourage users to consume them directly.

**Comment by morgante** [comment]
You can see the impact of this on the registry where submodules without a README are (correctly) marked as "internal": https://registry.terraform.io/modules/terraform-google-modules/forseti/google/3.0.0

**Comment by hshin-g** [comment]
That is a fair point- no READMEs for internal modules. Thanks!

**Pull request merged**
