### PR TITLE
Extract network setup from examples

### PR DESCRIPTION
**Pull request by aaron-lane**
This pull request is paired with https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/260.

### CODE REVIEW

**Comment by aaron-lane** [comment]
This is a temporary fix to address the consistent failures of the existing pipeline until we can migrate to our new approach.

**Comment by aaron-lane** [comment]
@morgante I had to make some additional commits as the initial branch was not functionally complete. I have opened #221 and #222 to address failures in the controls of various suites but this branch has solved the issue of suites failing due to networking issues during `terraform apply`.

**Comment by hshin-g** [comment]
@aaron-lane Can we merge this?

**Comment by aaron-lane** [comment]
Merging as CI failures are expected.

**Pull request merged**
