### PR TITLE
support Cloud SQL instance on private network

### PR DESCRIPTION
**Pull request by katze120**
hi, this PR is to support the enabling of private network on Cloud SQL instance during creation.

Needed this especially for deployments on shared VPC because "GCP does not allow you to assign a private IP address for an existing Cloud SQL instance to an address in a Shared VPC network" according to [documentation](https://cloud.google.com/sql/docs/mysql/private-ip#network_requirements)

I see that private VMs are being handled in #76 hence did not cover that in this PR.

### CODE REVIEW

**Comment by ocervell** [comment]
@katze120 Any reason for closing this ? I think this could be useful and complement #76 . @morgante, @aaron-lane - thoughts ?

**Comment by katze120** [comment]
The PR didn't pass the CI test and I need more time to figure out why.
Probably issue is related to tf or provider versions but I need to find
time after this week to test further, hence closing it first.
I do plan to reopen once I'm more confident of passing CI test.

**Comment by kevensen** [comment]
@katze120 when you have an opportunity, do you mind taking a look at the merge conflicts?

**Comment by kevensen** [comment]
@katze120 @ocervell @morgante @aaron-lane What is required to get this PR over the finish line?

**Comment by morgante** [comment]
Merge conflicts need to be fixed and CI verified.

**Comment by kevensen** [comment]
I recommend closing this issue in favor of #228 .  I've ported over the changes to that PR.

**Pull request closed without merging**
